name: Coverage Report

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Test and Send Report
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build
        run: ./gradlew test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
